# Generated by Django 4.2.3 on 2023-07-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
