# Generated by Django 4.2.3 on 2023-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Catalyst Fantasy Football', max_length=255),
        ),
    ]
