# Generated by Django 4.2.3 on 2023-07-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0006_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
