# Generated by Django 4.2.3 on 2023-07-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0007_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='drafted',
            field=models.BooleanField(default=False),
        ),
    ]
