# Generated by Django 4.2.3 on 2023-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0008_player_drafted'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='positional_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
