# Generated by Django 4.2.3 on 2023-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0009_player_positional_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='positional_rank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(max_length=255),
        ),
    ]
