# Generated by Django 4.2.3 on 2023-07-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0011_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='adp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='positional_rank',
            field=models.CharField(default='', max_length=255),
        ),
    ]
