# Generated by Django 4.2.3 on 2023-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0013_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
