# Generated by Django 4.2.3 on 2023-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0015_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='img_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
