# Generated by Django 4.2.3 on 2025-08-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0017_post_podcast_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bye',
            field=models.IntegerField(default=0),
        ),
    ]
