# Generated by Django 4.2.3 on 2026-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0018_player_bye'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
