# Generated by Django 4.2.3 on 2026-08-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0019_delete_category_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('overall_pick', models.PositiveSmallIntegerField(unique=True)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_pick', to='cffapp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='cffapp.fantasyteam')),
            ],
            options={
                'ordering': ['overall_pick'],
                'unique_together': {('round_number', 'team')},
            },
        ),
    ]
