# Generated by Django 4.2.3 on 2026-08-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0020_fantasyteam_draftpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='board_positional_rank',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='board_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
