# Generated by Django 4.2.3 on 2026-08-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffapp', '0021_player_board_positional_rank_player_board_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='is_my_team',
            field=models.BooleanField(default=False),
        ),
    ]
